### ISSUE TITLE
OP Sweden

### ISSUE THREAD

**Issue by Blagolepny** [MaTi5893/AoE-mp-remake#1]
Can't f***ing beat Sweden as playing Russia, at all, she beats mine armies even if they're 90k of mine vs 30k of their infantry, i understand that they have an a "proffesionalism" but you know in a game it's just like they are a super humans, even if i join with Norway - i get f**ked as well as Norway get f**ked too. Give them less professionalism, or idk, less armies and abilites to f*** everything. Please. It's just unplayable for me at this point, i love Russia, but can't play as her

**Comment by MaTi5893** [comment]
tech up, build up, i've seen succesfull russias in both sp and mp, even making one myself
